CC = gcc
CFLAGS = -Wall -Werror
ALL = 1-1 1-3 1-4 1-5 1-8 1-9 1-10 1-12 1-13 1-14 1-17 1-18 1-19 1-20 1-21

all : $(ALL)

1-18 : fun.c fun.h

1-19 : fun.c fun.h

% : %.o

clean : 
	rm -rf *.txt *.o $(ALL)
